[package]
name = "rawrwm"
version = "0.1.0"
authors = ["Dom Rodriguez <shymega@shymega.org.uk>"]
edition = "2018"

[[bin]]
name = "rawrwmd"

[dependencies]
serde = "1.0.126"
serde_derive = "1.0.126"
serde_json = "1.0.64"
log = "0.4.14"
tokio = "1.6.1"
futures = "0.3.15"
slog = "2.7.0"
slog-scope = "4.4.0"
slog-async = "2.6.0"
jsonrpc = "0.12.0"
jsonrpc-ipc-server = "17.0.1"

[dependencies.rawrwm_backends_wayland]
path = "../../lib/backends/wayland"

[dependencies.rawrwm_backends_x11]
path = "../../lib/backends/x11"

[dependencies.rawrwm_utils]
path = "../../lib/utils"

# slog and other deps derived from leftwm, thanks!
[features]
default = ["slog-term"]
journald = ["slog-journald"]

[dependencies.slog-journald]
version = "2.1.1"
optional = true

[dependencies.slog-term]
version = "2.8.0"
optional = true

[dependencies.clap]
features = ["suggestions", "color", "wrap_help"]
version = "2.33.3"
