[package]
name = "rawrctl"
version = "0.1.0"
authors = ["Dom Rodriguez <shymega@shymega.org.uk>"]
edition = "2021"

[[bin]]
name = "rawrctl"
path = "src/main.rs"

[dependencies]
serde = "1.0.152"
serde_derive = "1.0.151"
serde_json = "1.0.91"
tokio = "1.24.2"
futures = "0.3.25"
slog = "2.7.0"
slog-async = "2.7.0"
slog-term = "2.9.0"
jsonrpc-core-client = "18.0.0"

[dependencies.clap]
features = ["suggestions", "color", "wrap_help"]
version = "4.1.4"

[dependencies.rawrwm_rpc]
path = "../../src/rpc"
