[package]
name = "rawrctl"
version = "0.1.0"
authors = ["Dom Rodriguez <shymega@shymega.org.uk>"]
edition = "2018"

[[bin]]
name = "rawrctl"
path = "src/main.rs"

[dependencies]
serde = "1.0.126"
serde_derive = "1.0.126"
serde_json = "1.0.64"
tokio = "1.8.1"
futures = "0.3.15"
slog = "2.7.0"
slog-async = "2.6.0"
slog-term = "*"
jsonrpc-core-client = "18.0.0"

[dependencies.clap]
features = ["suggestions", "color", "wrap_help"]
version = "2.33.3"

[dependencies.rawrwm_rpc]
path = "../../lib/rpc"
