# SPDX-FileCopyrightText: 2023 The RawrWM Developers
#
# SPDX-License-Identifier: Apache-2.0

[package]
name = "rawrd"
version = "0.1.0"
authors = ["Dom Rodriguez <shymega@shymega.org.uk>"]
edition = "2021"

[[bin]]
name = "rawrd"
path = "src/main.rs"

[dependencies]
log = "0.4.19"
tokio = { version = "1.29.1", features = ["full"] }
env_logger = "0.10.0"

[dependencies.rawrwm-core]
path = "../../core"

[dependencies.clap]
features = ["suggestions", "color", "wrap_help"]
version = "4.3.19"
