# SPDX-FileCopyrightText: 2023 The RawrWM Developers
#
# SPDX-License-Identifier: Apache-2.0

[package]
name = "rawrd"
version = "0.1.0"
authors = ["Dom Rodriguez <shymega@shymega.org.uk>"]
edition = "2021"

[[bin]]
name = "rawrd"
path = "src/main.rs"

[dependencies]
serde = "1.0.175"
serde_derive = "1.0.175"
serde_json = "1.0.103"
log = "0.4.19"
tokio = { version = "1.29.1", features = ["full"] }
futures = "0.3.28"
anyhow = "1.0.72"
thiserror = "1.0.44"
jsonrpc = "0.16.0"
jsonrpc-ipc-server = "18.0.0"

[dependencies.rawrwm-core]
path = "../../core"

[dependencies.clap]
features = ["suggestions", "color", "wrap_help"]
version = "4.3.19"
