# SPDX-FileCopyrightText: 2023 The RawrWM Developers
#
# SPDX-License-Identifier: Apache-2.0

[package]
name = "rawrctl"
version = "0.1.0"
authors = ["Dom Rodriguez <shymega@shymega.org.uk>"]
edition = "2021"

[[bin]]
name = "rawrctl"
path = "src/main.rs"

[dependencies]
env_logger = "0.10.0"
log = "0.4.19"

[dependencies.clap]
features = ["suggestions", "color", "wrap_help"]
version = "4.3.19"

[dependencies.rawrwm-core]
path = "../../core"
