[package]
name = "rawrd"
version = "0.1.0"
authors = ["Dom Rodriguez <shymega@shymega.org.uk>"]
edition = "2021"

[[bin]]
name = "rawrd"
path = "src/main.rs"

[dependencies]
serde = "1.0.152"
serde_derive = "1.0.151"
serde_json = "1.0.91"
log = "0.4.17"
tokio = { version = "1.25.0", features = ["full"] }
futures = "0.3.25"
anyhow = "1.0.68"
thiserror = "1.0.38"
slog = "2.7.0"
slog-async = "2.7.0"
jsonrpc = "0.14.0"
jsonrpc-ipc-server = "18.0.0"

[dependencies.rawrwm_backend_wayland]
path = "../../src/backends/wayland"

[dependencies.rawrwm_backend_x11]
path = "../../src/backends/x11"

[dependencies.rawrwm_utils]
path = "../../src/utils"

[dependencies.slog-journald]
version = "2.2.0"
optional = true

[dependencies.slog-term]
version = "2.9.0"
optional = true

[dependencies.clap]
features = ["suggestions", "color", "wrap_help"]
version = "4.1.4"

# slog and other deps derived from leftwm, thanks!
[features]
default = ["slog-term"]
journald = ["slog-journald"]
