[package]
name = "rawrwm"
version = "0.1.0"
authors = ["Dom Rodriguez <shymega@shymega.org.uk>"]
edition = "2018"

[[bin]]
name = "rawrwm"

[dependencies]
serde = "1.0.117"
serde_derive = "1.0.117"
serde_json = "1.0.59"
log = "0.4.11"
tokio = "0.3.1"
futures = "0.3.7"
slog = "2.5.2"
slog-stdlog = "4.1.0"
slog-scope = "4.3.0"
slog-envlogger = "2.2.0"
slog-async = "2.5.0"
jsonrpc = "0.11.0"
jsonrpc-ipc-server = "15.1.0"

[dependencies.rawrwm_backends_wayland]
path = "../../lib/backends/wayland"

[dependencies.rawrwm_backends_x11]
path = "../../lib/backends/x11"

[dependencies.rawrwm_utils]
path = "../../lib/utils"

# slog and other deps derived from leftwm, thanks!
[features]
default = [
    "slog-term"
    ]
journald = [
    "slog-journald"
]
syslog = [
    "slog-syslog"
]

[dependencies.slog-journald]
version = "2.1.1"
optional = true

[dependencies.slog-term]
version = "2.6.0"
optional = true

[dependencies.slog-syslog]
version = "0.12.0"
optional = true

[dependencies.clippy]
version = "0.0.302"
optional = true

[dependencies.clap]
features = [
    "suggestions",
    "color",
    "wrap_help"
]
version = "2.33.3"
