# SPDX-FileCopyrightText: 2023 The RawrWM Developers
#
# SPDX-License-Identifier: Apache-2.0

name: RawrWM builder workflow

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install APT dependencies
        run: sudo apt-get update && sudo apt-get install -y libinput-dev libudev-dev libwayland-dev libx11-dev libsdl-pango-dev libdbus-1-dev pkg-config libsystemd-dev

      - name: Setup Rust (stable) toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build RawrWM (debug)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --locked --all

      - name: Upload Debug build binaries
        uses: actions/upload-artifact@v4
        with:
          name: RawrWM-debug-${{ github.ref_name }}
          path: |
            target/debug/rawrd
            target/debug/rawrctl
